
[env:tdeck]
platform = espressif32
board = t-deck
framework = arduino
monitor_speed = 115200
build_flags =
    -D BOARD_HAS_PSRAM=1
    -D CORE_DEBUG_LEVEL=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
extra_scripts = pre:custom_bootloader.py
lib_deps =
    adafruit/Adafruit SHARP Memory Display@^1.1.4
    adafruit/Adafruit GFX Library@^1.12.1
    adafruit/Adafruit ImageReader Library@^2.9.3
    adafruit/Adafruit SPIFlash@^5.1.1
    adafruit/SdFat - Adafruit Fork@^2.3.53